# Generated by Django 5.0 on 2024-01-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0019_anuncio_pantallas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='pantallas',
            new_name='pantallas_relacionadas',
        ),
    ]
