# Generated by Django 5.0 on 2024-01-26 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0020_rename_pantallas_anuncio_pantallas_relacionadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='pantallas_relacionadas',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='Pantalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuncios.pantalla'),
        ),
    ]
