# Generated by Django 5.0 on 2024-01-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0021_remove_anuncio_pantallas_relacionadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsevent',
            name='Anuncio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anuncios.anuncio'),
        ),
    ]
