# Generated by Django 5.0 on 2024-01-26 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0023_remove_anuncio_pantalla_remove_cmsevent_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='pantalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='anuncios.pantalla'),
        ),
        migrations.AddField(
            model_name='cmsevent',
            name='pantalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='anuncios.pantalla'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(max_length=17),
        ),
    ]
