# Generated by Django 5.0 on 2024-01-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0024_anuncio_pantalla_cmsevent_pantalla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='pantalla',
        ),
        migrations.RemoveField(
            model_name='cmsevent',
            name='pantalla',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('Archivo', 'Archivo'), ('Widgets', 'Widgets'), ('Lista Inteligente', 'Lista Inteligente')], max_length=17),
        ),
    ]
