# Generated by Django 5.0 on 2024-01-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0026_pantalla_anuncios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantalla',
            name='anuncios',
        ),
        migrations.AddField(
            model_name='pantalla',
            name='anuncios',
            field=models.ManyToManyField(blank=True, related_name='anuncios_pantalla', to='anuncios.anuncio'),
        ),
    ]
