# Generated by Django 5.0 on 2024-01-29 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0028_remove_pantalla_anuncios_pantalla_anuncios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantalla',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
