# Generated by Django 5.0 on 2024-01-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0029_pantalla_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantalla',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pantalla',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
