# Generated by Django 5.0 on 2024-02-01 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0030_pantalla_latitud_pantalla_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pantalla',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pantallas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
