# Generated by Django 5.0 on 2024-02-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0031_pantalla_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantalla',
            name='anuncios',
        ),
        migrations.AddField(
            model_name='pantalla',
            name='anuncios',
            field=models.ManyToManyField(related_name='pantallas', to='anuncios.anuncio'),
        ),
    ]
