# Generated by Django 5.0 on 2024-02-02 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0037_archivoanunciopantalla_pantalla_archivos_anuncios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantalla',
            name='archivos_anuncios',
        ),
        migrations.RemoveField(
            model_name='pantalla',
            name='anuncios',
        ),
        migrations.DeleteModel(
            name='ArchivoAnuncioPantalla',
        ),
        migrations.AddField(
            model_name='pantalla',
            name='anuncios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_pantalla', to='anuncios.anuncio'),
        ),
    ]
