# Generated by Django 5.0 on 2024-02-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0038_remove_pantalla_archivos_anuncios_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CMSEvent',
        ),
    ]
