# Generated by Django 5.0 on 2024-02-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0039_delete_cmsevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantalla',
            name='anuncios',
        ),
        migrations.AddField(
            model_name='pantalla',
            name='anuncios',
            field=models.ManyToManyField(blank=True, related_name='pantallas', to='anuncios.anuncio'),
        ),
    ]
