# Generated by Django 5.0 on 2024-02-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0041_remove_pantalla_anuncios_pantalla_anuncios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantalla',
            name='anuncios',
        ),
        migrations.AddField(
            model_name='pantalla',
            name='anuncios',
            field=models.ManyToManyField(blank=True, to='anuncios.anuncio'),
        ),
    ]
