# Generated by Django 5.0 on 2024-02-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0042_remove_pantalla_anuncios_pantalla_anuncios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='videos_imagenes')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='archivos',
            field=models.ManyToManyField(to='anuncios.archivo'),
        ),
    ]
