# Generated by Django 5.0 on 2024-02-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0043_archivo_anuncio_archivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='archivos',
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
