# Generated by Django 5.0 on 2024-02-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0044_remove_anuncio_archivos_delete_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='multiplefiles')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='multiplefile',
            field=models.ManyToManyField(blank=True, to='anuncios.multiplefile'),
        ),
    ]
