# Generated by Django 5.0 on 2024-02-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0045_multiplefile_anuncio_multiplefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='multiplefile',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='MultipleFile',
        ),
    ]
