# Generated by Django 5.0 on 2024-02-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0047_canvas_anuncio_canvas_listainteligente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='canvas',
        ),
        migrations.RemoveField(
            model_name='listainteligente',
            name='files',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='lista_inteligente',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('Archivo', 'Archivo'), ('Widgets', 'Widgets'), ('Lista Inteligente', 'Lista Inteligente')], default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Canvas',
        ),
        migrations.DeleteModel(
            name='ListaInteligente',
        ),
    ]
