# Generated by Django 5.0 on 2024-02-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0048_remove_anuncio_canvas_remove_listainteligente_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='videos_imagenes')),
                ('alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='file',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='files',
            field=models.ManyToManyField(to='anuncios.mediaarchivo'),
        ),
    ]
