# Generated by Django 5.0 on 2024-02-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0049_mediaarchivo_remove_anuncio_file_anuncio_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='files',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='file',
            field=models.FileField(null=True, upload_to='videos_imagenes'),
        ),
        migrations.DeleteModel(
            name='MediaArchivo',
        ),
    ]
